kernel bump: 3.4.51, 3.9.8 - grub bump

diff --git a/grub/PKGBUILD b/grub/PKGBUILD
--- a/grub/PKGBUILD
+++ b/grub/PKGBUILD
@@ -1,102 +1,97 @@
 # Based on the file created for Arch Linux by:
+# Tobias Powalowski <tpowa@archlinux.org>
 # Ronald van Haren <ronald.archlinux.org>
-# Keshav P R <(the.ridikulus.rat) (aatt) (gemmaeiil) (ddoott) (ccoomm)>
+# Keshav Padram <(the.ridikulus.rat) (aatt) (gemmaeiil) (ddoott) (ccoomm)>
 
-# Maintainer: Guinux <nuxgui@gmail.com>
+# Maintainer: Philip Mueller <philm|manjaro|org>
+# Maintainer: Guinux <nuxgui|gmail|com>
 
-_grub_lua_ver=24
-_grub_ntldr_ver=21
-_grub_915_ver=9
+_GRUB_BZR_REV="5043"
 
-pkgname=('grub-common' 'grub-bios' 'grub-efi-i386')
-pkgbase=grub
-pkgver=2.00
-pkgrel=5
+## grub-extras lua and gpxe fail to build with grub bzr rev 5043
+
+[[ "${CARCH}" == "x86_64" ]] && _EFI_ARCH="x86_64"
+[[ "${CARCH}" == "i686" ]] && _EFI_ARCH="i386"
+
+pkgname=grub
+pkgdesc="GNU GRand Unified Bootloader (2)"
+pkgver=2.00.${_GRUB_BZR_REV}
+pkgrel=2
 url="https://www.gnu.org/software/grub/"
-arch=('i686' 'x86_64')
+arch=('x86_64' 'i686')
 license=('GPL3')
-makedepends=('xz' 'bdf-unifont' 'ttf-dejavu' 'python' 'autogen'
-             'texinfo' 'help2man' 'gettext' 'device-mapper' 'fuse')
+backup=('boot/grub/grub.cfg' 'etc/default/grub' 'etc/grub.d/40_custom')
+install="${pkgname}.install"
+options=('!makeflags')
 
-source=("http://ftp.gnu.org/gnu/grub/grub-${pkgver}.tar.xz"
-        "ftp://ftp.archlinux.org/other/grub2/grub2_extras_lua_r${_grub_lua_ver}.tar.xz"
-        "ftp://ftp.archlinux.org/other/grub2/grub2_extras_ntldr-img_r${_grub_ntldr_ver}.tar.xz"
-        "ftp://ftp.archlinux.org/other/grub2/grub2_extras_915resolution_r${_grub_915_ver}.tar.xz"
+conflicts=('grub-common' 'grub-bios' 'grub-efi-i386' 'grub-efi-x86_64' 'grub-legacy')
+replaces=('grub-common' 'grub-bios' 'grub-efi-i386' 'grub-efi-x86_64')
+provides=('grub-common' 'grub-bios' 'grub-efi-i386' 'grub-efi-x86_64')
+
+makedepends=('xz' 'freetype2' 'bdf-unifont' 'ttf-dejavu' 'python' 'autogen'
+             'texinfo' 'help2man' 'gettext' 'device-mapper' 'fuse' 'bzr' 'rsync')
+depends=('sh' 'xz' 'gettext' 'device-mapper')
+optdepends=('freetype2: For grub-mkfont usage'
+            'fuse: For grub-mount usage'
+            'dosfstools: For grub-mkrescue FAT FS and EFI support' 
+            'efibootmgr: For grub-install EFI support'
+            'libisoburn: Provides xorriso for generating grub rescue iso using grub-mkrescue'
+            'os-prober: To detect other OSes when generating grub.cfg in BIOS systems'
+            'mtools: For grub-mkrescue FAT FS support')
+
+# source=("http://ftp.gnu.org/gnu/grub/grub-${pkgver}.tar.xz"
+source=("grub-${pkgver}::bzr+bzr://bzr.savannah.gnu.org/grub/trunk/grub/#revision=${_GRUB_BZR_REV}"
         'manjaro_grub_mkconfig_fixes.patch'
-        'background.png'
+        '60_memtest86+'
         'grub.default'
         'grub.cfg'
-        '20_memtest86+'
-        'grub_bzr_export.sh'
-        'update-grub'
-        '0069-Backport-gnulib-fixes-for-C11.-Fixes-Savannah-bug-37.patch'
-        'grub-2.00-fix-docs.patch')
+        'background.png'
+        'update-grub')
 
-noextract=("grub2_extras_lua_r${_grub_lua_ver}.tar.xz"
-           "grub2_extras_ntldr-img_r${_grub_ntldr_ver}.tar.xz"
-           "grub2_extras_915resolution_r${_grub_915_ver}.tar.xz")
+for _DIR_ in 915resolution ntldr-img ; do
+	source+=("grub-extras-${_DIR_}::bzr+bzr://bzr.savannah.gnu.org/grub-extras/${_DIR_}/#revision=")
+done
 
-sha256sums=('784ec38e7edc32239ad75b8e66df04dc8bfb26d88681bc9f627133a6eb85c458'
-            'bfe0318a9bb7edbaee2489b1396d0034791751b42035ea40ad61600fdf974df2'
-            '2b8b1112b67c2b8d0e46b87fd0a2597461ce4d4c80fc25d0a7319db94b6ac600'
-            '04f79ec649764b02444d9bd82b39814bd17f018abf00c8b34bbafa37899c3a3f'
-            '1b435e3a2c309afe4cc952dd8c5c7375ca180970b93f128bc283272e72f9928e'
-            '1b77925818a4f76df8453c3643513145f46f1738a2684f92304ea60637277d47'
-            '720db20a6a1c81864ad6405ef838db02206b53298fda48f383bebdb51eac56a8'
-            '7fc95d49c0febe98a76e56b606a280565cb736580adecf163bc6b5aca8e7cbd8'
-            '259d7eafa2751dd443cb3a08784ef444565cc487d427afa9a268e41bb6c5aba2'
-            '625b5d04726ae7f7af8924916171cc5a6ca30d82045e8ea93ac006a4043c8a54'
-            '467b0101154076fee99d9574a5fb6b772a3923cc200a1f4ca08fe17be8d68111'
-            '653444068540f0e693f22261058f6dba2d21982d9a697167b95aabb58879478d'
-            'b80045e2f9b89d7489b9bbd3d2e9692d4750d60c932fe7f31e0c7cc986bae489')
+# sha1sums=('274d91e96b56a5b9dd0a07accff69dbb6dfb596b'
+sha1sums=('SKIP'
+          '84a7d752e81326bbe573fe7d468f8e8bf06503b5'
+          '2aa2deeb7d7dc56f389aa1487b7a57b0d44ce559'
+          '80b3ed3ba71f09a1d1afb34441e5d3295ec21f20'
+          '19a6c2f10219a57c6f988f1bfa701b27d14cd381'
+          '63bec50c59bff0c46b42e7889952274c83d49f84'
+          '02838339939695b2fa73e2a487fda0f89498b58e'
+          'SKIP'
+          'SKIP')
 
 _build_grub-common_and_bios() {
-
-	## copy the source for building the common/bios package
-	cp -r "${srcdir}/grub-${pkgver}" "${srcdir}/grub_bios-${pkgver}"
-	cd "${srcdir}/grub_bios-${pkgver}"
-
-	# fix compiling with gcc48
-        patch -Np1 -i ${srcdir}/0069-Backport-gnulib-fixes-for-C11.-Fixes-Savannah-bug-37.patch
-
-	#fix docs compiling
-        patch -Np1 -i ${srcdir}/grub-2.00-fix-docs.patch
-
-	## Apply Manjaro Linux specific fixes to enable grub-mkconfig detect Manjaro kernels and initramfs
-	patch -Np1 -i "${srcdir}/manjaro_grub_mkconfig_fixes.patch"
-	echo
-
-	## fix unifont.bdf location so that grub-mkfont can create *.pf2 files
-	sed 's|/usr/share/fonts/unifont|/usr/share/fonts/unifont /usr/share/fonts/misc|g' -i "${srcdir}/grub_bios-${pkgver}/configure.ac"
-
-	## fix DejaVuSans.ttf location so that grub-mkfont can create *.pf2 files for starfield theme
-	sed 's|/usr/share/fonts/dejavu|/usr/share/fonts/dejavu /usr/share/fonts/TTF|g' -i "${srcdir}/grub_bios-${pkgver}/configure.ac"
-
-	## add the grub-extra sources
-	export GRUB_CONTRIB="${srcdir}/grub_bios-${pkgver}/grub-extras/"
-	install -d "${srcdir}/grub_bios-${pkgver}/grub-extras"
-
-	bsdtar xf "${srcdir}/grub2_extras_lua_r${_grub_lua_ver}.tar.xz" \
-		-C "${srcdir}/grub_bios-${pkgver}/grub-extras"
-
-	bsdtar xf "${srcdir}/grub2_extras_ntldr-img_r${_grub_ntldr_ver}.tar.xz" \
-		-C "${srcdir}/grub_bios-${pkgver}/grub-extras"
-
-	bsdtar xf "${srcdir}/grub2_extras_915resolution_r${_grub_915_ver}.tar.xz" \
-		-C "${srcdir}/grub_bios-${pkgver}/grub-extras"
-
-	## Requires python2
-	# sed 's|python |python2 |g' -i "${srcdir}/grub_bios-${pkgver}/autogen.sh"
-
-	## start the actual build process
-	cd "${srcdir}/grub_bios-${pkgver}"
+	
+	## Copy the source for building the common/bios package
+	cp -r "${srcdir}/grub-${pkgver}" "${srcdir}/grub-${pkgver}-bios"
+	cd "${srcdir}/grub-${pkgver}-bios/"
+	
+	## Add the grub-extra sources
+	export GRUB_CONTRIB="${srcdir}/grub-${pkgver}-bios/grub-extras/"
+	
+	install -d "${srcdir}/grub-${pkgver}-bios/grub-extras"
+	for _DIR_ in 915resolution ntldr-img ; do
+		cp -r "${srcdir}/grub-extras-${_DIR_}" "${srcdir}/grub-${pkgver}-bios/grub-extras/${_DIR_}"
+	done
+	
+	## Unset all compiler FLAGS for bios build
+	unset CFLAGS
+	unset CPPFLAGS
+	unset CXXFLAGS
+	unset LDFLAGS
+	unset MAKEFLAGS
+	
+	## Start the actual build process
+	cd "${srcdir}/grub-${pkgver}-bios/"
 	./autogen.sh
 	echo
-
-	CFLAGS="" ./configure \
+	
+	./configure \
 		--with-platform="pc" \
 		--target="i386" \
-		--host="${CARCH}-unknown-linux-gnu" \
 		"${_EFIEMU}" \
 		--enable-mm-debug \
 		--enable-nls \
@@ -111,44 +106,43 @@ _build_grub-common_and_bios() {
 		--infodir="/usr/share/info" \
 		--datarootdir="/usr/share" \
 		--sysconfdir="/etc" \
-		--program-prefix="" \
+	 	--program-prefix="" \
 		--with-bootdir="/boot" \
 		--with-grubdir="grub" \
 		--disable-werror
 	echo
-
-	CFLAGS="" make
+	
+	make
 	echo
-
 }
 
-_build_grub-efi-i386() {
-
-	## copy the source for building the efi package
-	cp -r "${srcdir}/grub-${pkgver}" "${srcdir}/grub_efi-${pkgver}"
-
-	cd "${srcdir}/grub_efi-${pkgver}"
-
-	export GRUB_CONTRIB="${srcdir}/grub_efi-${pkgver}/grub-extras/"
-	install -d "${srcdir}/grub_efi-${pkgver}/grub-extras"
-
-	bsdtar xf "${srcdir}/grub2_extras_lua_r${_grub_lua_ver}.tar.xz" \
-		-C "${srcdir}/grub_efi-${pkgver}/grub-extras"
-
-	# fix compiling with gcc48
-        patch -Np1 -i ${srcdir}/0069-Backport-gnulib-fixes-for-C11.-Fixes-Savannah-bug-37.patch
-
-	#fix docs compiling
-        patch -Np1 -i ${srcdir}/grub-2.00-fix-docs.patch
-
-	cd "${srcdir}/grub_efi-${pkgver}"
+_build_grub-efi() {
+	
+	## Copy the source for building the efi package
+	cp -r "${srcdir}/grub-${pkgver}" "${srcdir}/grub-${pkgver}-efi"
+	cd "${srcdir}/grub-${pkgver}-efi/"
+	
+	# export GRUB_CONTRIB="${srcdir}/grub-${pkgver}-efi/grub-extras/"
+	
+	# install -d "${srcdir}/grub-${pkgver}-efi/grub-extras/"
+	# for _DIR_ in lua gpxe ; do
+	#	cp -r "${srcdir}/grub-extras-${_DIR_}" "${srcdir}/grub-${pkgver}-bios/grub-extras/${_DIR_}"
+	# done
+	
+	## Unset all compiler FLAGS for efi build
+	unset CFLAGS
+	unset CPPFLAGS
+	unset CXXFLAGS
+	unset LDFLAGS
+	unset MAKEFLAGS
+	
+	cd "${srcdir}/grub-${pkgver}-efi/"
 	./autogen.sh
 	echo
-
-	CFLAGS="" ./configure \
+	
+	./configure \
 		--with-platform="efi" \
-		--target="i386" \
-		--host="${CARCH}-unknown-linux-gnu" \
+		--target="${_EFI_ARCH}" \
 		--disable-efiemu \
 		--enable-mm-debug \
 		--enable-nls \
@@ -168,58 +162,69 @@ _build_grub-efi-i386() {
 		--with-grubdir="grub" \
 		--disable-werror
 	echo
-
-	CFLAGS="" make
+	
+	make
 	echo
-
+	
 }
 
 build() {
-
-	## set architecture dependent variables
+	
+	## Set ARCH dependent variables
 	if [[ "${CARCH}" == 'x86_64' ]]; then
 		_EFIEMU="--enable-efiemu"
 	else
 		_EFIEMU="--disable-efiemu"
 	fi
+	
+	cd "${srcdir}/grub-${pkgver}/"
+	
+	## Apply Manjaro Linux specific fixes to enable grub-mkconfig detect Manjaro kernels and initramfs
+	patch -Np1 -i "${srcdir}/manjaro_grub_mkconfig_fixes.patch"
+	echo
+	
+	## fix unifont.bdf location so that grub-mkfont can create *.pf2 files
+	sed 's|/usr/share/fonts/unifont|/usr/share/fonts/unifont /usr/share/fonts/misc|g' -i "${srcdir}/grub-${pkgver}/configure.ac"
+	
+	## fix DejaVuSans.ttf location so that grub-mkfont can create *.pf2 files for starfield theme
+	sed 's|/usr/share/fonts/dejavu|/usr/share/fonts/dejavu /usr/share/fonts/TTF|g' -i "${srcdir}/grub-${pkgver}/configure.ac"
+	
+	## Requires python2
+	# sed 's|python |python2 |g' -i "${srcdir}/grub-${pkgver}/autogen.sh"
 
-	_HOST="${CARCH}"
-
-	cd "${srcdir}/grub-${pkgver}"
-	# _get_locale_files
-
+        ## pull in language files
+        ./linguas.sh
+        # remove not working langs which need LC_ALL=C.UTF-8
+        sed -i -e 's#en@cyrillic en@greek##g' po/LINGUAS
 	_build_grub-common_and_bios
 	echo
-
-	_build_grub-efi-i386
+	
+	_build_grub-efi
 	echo
 
 }
 
-package_grub-common() {
-
-	pkgdesc="GNU GRand Unified Bootloader - Utilities and Common Files"
-	depends=('sh' 'xz' 'freetype2' 'gettext' 'device-mapper' 'fuse' 'os-prober')
-	conflicts=('grub-legacy' 'grub')
-	replaces=('grub2-common')
-	provides=('grub2-common')
-	backup=('boot/grub/grub.cfg' 'etc/default/grub' 'etc/grub.d/40_custom')
-	optdepends=('libisoburn: provides xorriso for generating grub rescue iso using grub-mkrescue'
-	            'mtools: for grub-mkrescue FAT FS support')
-	install="grub.install"
-	options=('strip' 'purge' 'docs' 'zipman' '!emptydirs')
-
-	cd "${srcdir}/grub_bios-${pkgver}"
+_package_grub-common_and_bios() {
+	
+	cd "${srcdir}/grub-${pkgver}-bios/"
 	make DESTDIR="${pkgdir}/" bashcompletiondir="/usr/share/bash-completion/completions" install
 	echo
-
-	## install extra /etc/grub.d/ files
-	install -D -m0755 "${srcdir}/20_memtest86+" "${pkgdir}/etc/grub.d/20_memtest86+"
-
-	## install /etc/default/grub (used by grub-mkconfig)
+	
+	## remove gdb debugging related files
+	rm -f "${pkgdir}/usr/lib/grub/i386-pc"/*.module || true
+	rm -f "${pkgdir}/usr/lib/grub/i386-pc"/*.image || true
+	rm -f "${pkgdir}/usr/lib/grub/i386-pc"/{kernel.exec,gdb_grub,gmodule.pl} || true
+	
+	## Fix OS naming FS#33393
+	sed 's|GNU/Linux|Linux|' -i "${pkgdir}/etc/grub.d/10_linux"
+	
+	## Install extra /etc/grub.d/ files
+	install -D -m0755 "${srcdir}/60_memtest86+" "${pkgdir}/etc/grub.d/60_memtest86+"
+	
+	## Install /etc/default/grub (used by grub-mkconfig)
 	install -D -m0644 "${srcdir}/grub.default" "${pkgdir}/etc/default/grub"
-
-	## install grub.cfg (needed so it doesn't get removed on upgrading because it was previously here)
+	
+	## Install grub.cfg for backup array
 	install -D -m0644 "${srcdir}/grub.cfg" "${pkgdir}/boot/grub/grub.cfg"
 
 	## install update-grub
@@ -227,52 +232,26 @@ package_grub-common() {
 
 	## install grub background
 	install -Dm644 "${srcdir}/background.png" "${pkgdir}/usr/share/grub/background.png"
-
-	# remove platform specific files
-	rm -rf "${pkgdir}/usr/lib/grub/i386-pc/"
-
+	
 }
 
-package_grub-bios() {
-
-	pkgdesc="GNU GRand Unified Bootloader - i386 PC BIOS Modules"
-	depends=("grub-common=${pkgver}")
-	options=('!strip' '!emptydirs')
-	replaces=('grub2-bios')
-	provides=('grub2-bios')
-
-	cd "${srcdir}/grub_bios-${pkgver}"
-	make DESTDIR="${pkgdir}/" install
+_package_grub-efi() {
+	
+	cd "${srcdir}/grub-${pkgver}-efi/"
+	make DESTDIR="${pkgdir}/" bashcompletiondir="/usr/share/bash-completion/completions" install
 	echo
-
-	## remove non platform-specific files
-	rm -rf "${pkgdir}"/{boot,etc,usr/{share,bin,sbin}}
-
+	
 	## remove gdb debugging related files
-	rm -f "${pkgdir}/usr/lib/grub/i386-pc"/*.module || true
-	rm -f "${pkgdir}/usr/lib/grub/i386-pc"/*.image || true
-	rm -f "${pkgdir}/usr/lib/grub/i386-pc"/{kernel.exec,gdb_grub,gmodule.pl} || true
-
+	rm -f "${pkgdir}/usr/lib/grub/${_EFI_ARCH}-efi"/*.module || true
+	rm -f "${pkgdir}/usr/lib/grub/${_EFI_ARCH}-efi"/*.image || true
+	rm -f "${pkgdir}/usr/lib/grub/${_EFI_ARCH}-efi"/{kernel.exec,gdb_grub,gmodule.pl} || true
+	
 }
 
-package_grub-efi-i386() {
-
-	pkgdesc="GNU GRand Unified Bootloader - i386 UEFI Modules"
-	depends=("grub-common=${pkgver}" 'dosfstools' 'efibootmgr')
-	options=('!strip' '!emptydirs')
-	replaces=('grub2-efi-i386')
-	provides=('grub2-efi-i386')
-
-	cd "${srcdir}/grub_efi-${pkgver}"
-	make DESTDIR="${pkgdir}/" install
-	echo
-
-	## remove non platform-specific files
-	rm -rf "${pkgdir}"/{boot,etc,usr/{share,bin,sbin}}
-
-	## remove gdb debugging related files
-	rm -f "${pkgdir}/usr/lib/grub/i386-efi"/*.module || true
-	rm -f "${pkgdir}/usr/lib/grub/i386-efi"/*.image || true
-	rm -f "${pkgdir}/usr/lib/grub/i386-efi"/{kernel.exec,gdb_grub,gmodule.pl} || true
-
+package() {
+	
+	_package_grub-efi
+	
+	_package_grub-common_and_bios
+	
 }
